---
title: "Susceptibility"
output: html_notebook
---
## Hierarchical Clustering Analysis for Susceptibility

```{r load packages, results='hide',message=FALSE, warning=FALSE}
library(FD)         # gower dissimiliarity matrix and some other 
#clustering stuff
library(ggplot2)    # plotting
library(vegan)      # stats
library(tidyverse)  # data manipulation
#cluster numbers
library(mclust)     # normal mixture modeling for model based clustering,
#customize denddrogram
library(dendextend) 
library(ggdendro)
library(patchwork)
```

Summarize all individual results by DEP.Genotype
```{r}
alldf<-read.csv("CombinedExperimentsIndividuals_V032024.csv",row.names = 1)

#first need a binary result: 1 diseased/removed at end, 0 if healthy
for (i in 1:nrow(alldf)){
  if(alldf$Result[i]=="Healthy"){
    alldf$ResultBinary[i]<-0
  }else(alldf$ResultBinary[i]<-1)
}

alldf$ResultBinary<-as.numeric(alldf$ResultBinary)
numremoveddf<-aggregate(ResultBinary~DEP.Genotype,data=alldf,FUN=sum)
numexposeddf<-aggregate(Result~DEP.Genotype,data=alldf,FUN=length)

DEPsummary<-cbind(numexposeddf,numremoveddf$ResultBinary)
colnames(DEPsummary)<-c("DEP.Genotype","Num.Exposed","Num.Removed")
DEPsummary$Num.healthy<-DEPsummary$Num.Exposed-DEPsummary$Num.Removed
summary(DEPsummary)
resdf<-right_join(DEPsummary,alldf,by=c("DEP.Genotype"="DEP.Genotype"))
resdf[resdf$Result=="Diseased",]$Result<-"Removed"
```
exp1 = 14days
exp2 = 11days
exp3 = 16days
exp4 = 18days
```{r}

head(resdf)
resdf$DEP.Genotype<-as.factor(resdf$DEP.Genotype)

resdf$Result<-as.factor(resdf$Result)
resdf$Experiment<-as.factor(resdf$Experiment)
#add in the number days per experiment
explengths<-c(14,11,16,18)
exps<-levels(resdf$Experiment)
expdf<-data.frame(exps,explengths)
resdf$ExpLength<-expdf[match(resdf$Experiment,expdf$exps),]$explengths

#standardize the days to disease by experiment length: how much of the experiment length was the coral healthy --> 0 diseased immediately to 1 never diseased --> measure of same thing as DaysToDisease.std but now 1 is resistant
resdf$FracExpHealthy<-resdf$Daystodisease/resdf$ExpLength 
resdf$FracExpHealthy<-replace_na(resdf$FracExpHealthy,1)

#standardize the days spent diseased by experiment length --> 0 is highly susceptible to 1 is resistant
resdf$DaysDiseased.std<-resdf$Daysdiseased/resdf$ExpLength
max(resdf$DaysDiseased.std,na.rm=T)
resdf$DaysDiseased.std<-replace_na(resdf$DaysDiseased.std,1)

```



```{r}
levels(resdf$Result)

GenoDF<-(as.data.frame.matrix(table(resdf$DEP.Genotype,resdf$Result)))
GenoDF$Exposed<-GenoDF$Healthy+GenoDF$Removed
GenoDF
GenoDF$DEP.Genotype<-as.factor(rownames(GenoDF))

daysdis<-aggregate(DaysDiseased.std~DEP.Genotype,data=resdf,FUN=mean,na.rm=TRUE)
FracExpHealthy<-aggregate(FracExpHealthy~DEP.Genotype,data=resdf,FUN=mean,na.rm=TRUE)

GenoDF$avgDaysDiseased.std<-daysdis$DaysDiseased.std
GenoDF$avgFracExpHealthy<-FracExpHealthy$FracExpHealthy
GenoDF$FracDiseased<-GenoDF$Removed/GenoDF$Exposed
GenoDF$FracHealthy<-GenoDF$Healthy/GenoDF$Exposed

GenoDF
write.csv(GenoDF,"RiskbyDEPGenotype_V032024.csv")
plot(GenoDF$avgDaysDiseased,GenoDF$FracDiseased)
```
## can start here
```{r}
GenoDF<-read.csv("RiskbyDEPGenotype_V032024.csv",row.names = 1)
```



```{r,fig.width=10,fig.height=4}

data_gdisall<-gowdis(GenoDF[,c(5,6,8)])
hc_gowdisall <- hclust(data_gdisall, method = "ward.D2" )
dendall <- as.dendrogram(hc_gowdisall)
dendall

par(cex=0.4, mar=c(10, 5, 5, 2))
plot(dendall, xlab="", ylab="", main="", sub="", axes=FALSE)
par(cex=.7)
title(xlab="Genotypes", ylab="Clustering Height")
axis(2)

dall<-dendro_data(dendall,type="rectangle")
groupsall<-cutree(hc_gowdisall,4)
GenoDF$sus.groups<-as.factor(groupsall)
GenoDF[order(GenoDF[,9],decreasing=T),]
labs<-right_join(dall$labels,GenoDF,by=c("label"="DEP.Genotype"))

alldendplot<-ggplot(dall$segments) + 
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend))+
  geom_text(data = dall$labels, aes(x, y, label = label,color=labs$sus.groups),
            hjust = 1.2, angle = 90, size = 2)+
  geom_point(data = dall$labels, aes(x, y,color=labs$sus.groups),size=.5)+
  scale_y_continuous(limits=c(-1,4.5),breaks=seq(0,4.5,0.5))+
  theme_bw()+
  scale_color_manual(values=c("violet","purple","steelblue3","darkblue"))+
  theme(legend.position = "bottom")+labs(color="Cluster",y="Clustering Height",x="")+
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())+guides(color=guide_legend(override.aes = list(size=5)))

alldendplot
```

```{r,fig.width=9,fig.height=3}
p1<-ggplot(GenoDF,aes(x=sus.groups,y=avgDaysDiseased.std,fill=sus.groups))+
  geom_boxplot()+
  scale_fill_manual(values=c("violet","purple","steelblue3","darkblue"))+
  theme_bw()+
  theme(legend.position = 'none')+labs(x="Cluster",y="Avg #Days Diseased")
p2<-ggplot(GenoDF,aes(x=sus.groups,y=avgFracExpHealthy,fill=sus.groups))+
  geom_boxplot()+
  scale_fill_manual(values=c("violet","purple","steelblue3","darkblue"))+
  theme_bw()+
  theme(legend.position = 'none')+labs(x="Cluster",y="Avg #Days until Disease Signs")
p3<-ggplot(GenoDF,aes(x=sus.groups,y=FracHealthy,fill=sus.groups))+
  geom_boxplot()+
  scale_fill_manual(values=c("violet","purple","steelblue3","darkblue"))+
  theme_bw()+
  theme(legend.position = 'none')+labs(x="Cluster",y="Fraction Resistant")

p1+p2+p3
```
```{r,fig.width=10,fig.height=6}
alldendplot/(p3+p1+p2)
ggsave("AllDEPGenos.png",dpi=300)
```

```{r}
Rcats<-c("Susceptible","Highly Susceptible","Intermediate","Resistant")
clusters<-levels(GenoDF$sus.groups)
clusterdata<-data.frame(Rcats,clusters)
GenoDF$Rcats<-clusterdata[match(GenoDF$sus.groups,clusterdata$clusters),]$Rcats
head(GenoDF)
```

### Those with 2 or more replicates
```{r,fig.width=12,fig.height=6}
GenoDFsub2<-subset(GenoDF,subset=Exposed>1)
data_gdis<-gowdis(GenoDFsub2[,c(5,6,8)])
hc_gowdis <- hclust(data_gdis, method = "ward.D2" )
dend2 <- as.dendrogram(hc_gowdis)
dend2

plot(dend2,xlab="Putative Genotypes",ylab="Clustering Height")

par(cex=0.7, mar=c(10, 5, 5, 2))
plot(dend2, xlab="", ylab="", main="", sub="", axes=FALSE)
par(cex=.9)
title(xlab="Genotypes", ylab="Clustering Height")
axis(2)

col_dend2 <- color_branches(dend2, k = 4)
plot(col_dend2,xlab="Putative Genotypes",ylab="Clustering Height")
dend2 %>% set("labels_col", value = c("violet","purple","steelblue3","darkblue"), k=4,ordered=T)%>% plot()


d2<-dendro_data(dend2,type="rectangle")
groups2<-cutree(hc_gowdis,4)
GenoDFsub2$sus.groups<-as.factor(groups2)

labs<-right_join(d2$labels,GenoDFsub2,by=c("label"="DEP.Genotype"))

Twodendplot<-ggplot(d2$segments) + 
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend))+
  geom_text(data = d2$labels, aes(x, y, label = label,color=labs$sus.groups),
            hjust = 1.2, angle = 90, size = 3)+
  geom_point(data = d2$labels, aes(x, y,color=labs$sus.groups),size=0.5)+
  scale_y_continuous(limits=c(-1,3.25),breaks=seq(0,3.25,0.5))+
  theme_bw()+
  scale_color_manual(values=c("violet","purple","steelblue3","darkblue"))+
  theme(legend.position = "bottom")+labs(color="Cluster",y="Clustering Height",x="")+
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())+guides(color=guide_legend(override.aes = list(size=5)))
Twodendplot
```

```{r,fig.width=9,fig.height=3}
p1<-ggplot(GenoDFsub2,aes(x=sus.groups,y=avgDaysDiseased.std,fill=sus.groups))+
  geom_boxplot()+
  scale_fill_manual(values=c("violet","purple","steelblue3","darkblue"))+
  theme_bw()+
  theme(legend.position = 'none')+labs(x="Cluster",y="Avg #Days Diseased")
p2<-ggplot(GenoDFsub2,aes(x=sus.groups,y=avgFracExpHealthy,fill=sus.groups))+
  geom_boxplot()+
  scale_fill_manual(values=c("violet","purple","steelblue3","darkblue"))+
  theme_bw()+
  theme(legend.position = 'none')+labs(x="Cluster",y="Avg #Days until Disease Signs")
p3<-ggplot(GenoDFsub2,aes(x=sus.groups,y=FracHealthy,fill=sus.groups))+
  geom_boxplot()+
  scale_fill_manual(values=c("violet","purple","steelblue3","darkblue"))+
  theme_bw()+
  theme(legend.position = 'none')+labs(x="Cluster",y="Fraction Resistant")

p1+p2+p3
```
```{r,fig.width=10,fig.height=6}
Twodendplot/(p3+p1+p2)
ggsave("TwoRepsDEPGenos.png",dpi=300)
```
```{r}
Rcats<-c("Susceptible","Highly Susceptible","Resistant","Intermediate")
clusters<-levels(GenoDFsub2$sus.groups)
clusterdata<-data.frame(Rcats,clusters)
GenoDFsub2$Rcats<-clusterdata[match(GenoDFsub2$sus.groups,clusterdata$clusters),]$Rcats
head(GenoDFsub2)
```

### those with 3 or more


```{r,fig.width=12,fig.height=6}
GenoDFsub3<-subset(GenoDF,subset=Exposed>2)
data_gdis<-gowdis(GenoDFsub3[,c(5,6,8)])
hc_gowdis <- hclust(data_gdis, method = "ward.D2" )
dend3 <- as.dendrogram(hc_gowdis)
dend3

plot(dend3,xlab="Putative Genotypes",ylab="Clustering Height")

par(cex=0.7, mar=c(10, 5, 5, 2))
plot(dend3, xlab="", ylab="", main="", sub="", axes=FALSE)
par(cex=.9)
title(xlab="Genotypes", ylab="Clustering Height")
axis(2)

col_dend <- color_branches(dend3, k = 4)
plot(col_dend,xlab="Putative Genotypes",ylab="Clustering Height")
dend3 %>% set("labels_col", value = c("violet","purple","steelblue3","darkblue"), k=4,ordered=T)%>% plot()


d3<-dendro_data(dend3,type="rectangle")
groups3<-cutree(hc_gowdis,4)
GenoDFsub3$sus.groups<-as.factor(groups3)

labs<-right_join(d3$labels,GenoDFsub3,by=c("label"="DEP.Genotype"))

Threedendplot<-ggplot(d3$segments) + 
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend))+
  geom_text(data = d3$labels, aes(x, y, label = label,color=labs$sus.groups),
            hjust = 1.2, angle = 90, size = 4)+
  geom_point(data = d3$labels, aes(x, y,color=labs$sus.groups),size=.5)+
  scale_y_continuous(limits=c(-1,2.5),breaks=seq(0,2.5,0.5))+
  theme_bw()+
  scale_color_manual(values=c("violet","purple","steelblue3","darkblue"))+
  theme(legend.position = "bottom")+labs(color="Cluster",y="Clustering Height",x="")+
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())+guides(color=guide_legend(override.aes = list(size=5)))
Threedendplot
```



```{r,fig.width=9,fig.height=3}
p1<-ggplot(GenoDFsub3,aes(x=sus.groups,y=avgDaysDiseased.std,fill=sus.groups))+
  geom_boxplot()+
  scale_fill_manual(values=c("violet","purple","steelblue3","darkblue"))+
  theme_bw()+
  theme(legend.position = 'none')+labs(x="Cluster",y="Avg #Days Diseased")
p2<-ggplot(GenoDFsub3,aes(x=sus.groups,y=avgFracExpHealthy,fill=sus.groups))+
  geom_boxplot()+
  scale_fill_manual(values=c("violet","purple","steelblue3","darkblue"))+
  theme_bw()+
  theme(legend.position = 'none')+labs(x="Cluster",y="Avg #Days until Disease Signs")
p3<-ggplot(GenoDFsub3,aes(x=sus.groups,y=FracHealthy,fill=sus.groups))+
  geom_boxplot()+
  scale_fill_manual(values=c("violet","purple","steelblue3","darkblue"))+
  theme_bw()+
  theme(legend.position = 'none')+labs(x="Cluster","Fraction Resistant")

p1+p2+p3
```

```{r,fig.width=10,fig.height=6}
Threedendplot/(p3+p1+p2)+plot_layout(heights = c(2,1))
ggsave("ThreeRepsDEPGenos.png",dpi=300)
```
```{r}
Rcats<-c("Highly Susceptible","Intermediate","Susceptible","Resistant")
clusters<-levels(GenoDFsub3$sus.groups)
clusterdata<-data.frame(Rcats,clusters)
GenoDFsub3$Rcats<-clusterdata[match(GenoDFsub3$sus.groups,clusterdata$clusters),]$Rcats
head(GenoDFsub3)
```
Combine all together to compare
```{r}
GenoDF$Rcats2reps<-GenoDFsub2[match(GenoDF$DEP.Genotype,GenoDFsub2$DEP.Genotype),]$Rcats
GenoDF$Rcats3reps<-GenoDFsub3[match(GenoDF$DEP.Genotype,GenoDFsub3$DEP.Genotype),]$Rcats
GenoDF$matches<-0
GenoDF$possible<-c()
for(i in 1:nrow(GenoDF)){
  if(!is.na(GenoDF$Rcats2reps[i]) & GenoDF$Rcats[i]==GenoDF$Rcats2reps[i]){
    GenoDF$matches[i]<-GenoDF$matches[i]+1
  }
  if(!is.na(GenoDF$Rcats3reps[i]) & GenoDF$Rcats[i]==GenoDF$Rcats3reps[i]){
    GenoDF$matches[i]<-GenoDF$matches[i]+1
  }
  GenoDF$possible[i]<-sum(!is.na(c(GenoDF$Rcats[i],GenoDF$Rcats2reps[i],GenoDF$Rcats3reps[i])))-1
}

GenoDF$fracmatched<-GenoDF$matches/GenoDF$possible
colnames(GenoDF)
GenoDFRanked<-GenoDF[,c(4,1:3,5:8,10:12,14)]

colnames(GenoDFRanked)<-c(colnames(GenoDFRanked)[c(1:8)],"RGroup.allclustered","RGroup.2ormorereps","RGroup.3ormorereps","FractionRGroupsMatched")
GenoDFRanked
write.csv(GenoDFRanked,"DEPGenotypes_SusceptibilityGroups_V03252024.csv")
```



